### ISSUE TITLE
Compatibility with Vivaldi Browser

### ISSUE THREAD

**Issue by fortbis** [Baldomo/open-in-mpv#25]
### Question Description

Previously created issue explaining why this doesn't work in the Vivaldi browser, and how it can be resolved.

_«Vivaldi uses LD_PRELOAD='' to load ffmpeg, and this causes an error with ffmpeg's mpv. Without LD_PRELOAD everything works fine.»_

Please suggest a way to solve this without breaking with every system update. Thanks!

### Checklist:

- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Baldomo** [comment]
This is not a problem which should be solved by this extension. I do not intend to modify system variables or, in general, the user's environment. Thanks to #26 you can launch the player by setting the `executable` configuration field to something like `env -u LD_PRELOAD mpv`, which will launch mpv by unsetting LD_PRELOAD. I **don't recommend** doing it because stuff might break inside Vivaldi, you should probably create a wrapper script and put that in `executable`. This is something that should be configurable in Vivaldi.
