### ISSUE TITLE
feature: Specify working directory

### ISSUE THREAD

**Issue by Tremolo4** [Baldomo/open-in-mpv#31]
### Feature Description

I'd like to be able to specify the working directory that the player executable is executed in.

Currently, on windows, open-in-mpv starts players in `C:\Windows\system32`.

### Additional Context (optional)

For some reason mpv/yt-dlp fails to play some, but not all, youtube videos if it is started from a non-writable directory. \*

It would be cool if open-in-mpv could by default start players from the users home directory instead of `C:\Windows\system32`.
Or at least have an option to specify the working directory.

For now, I'm using the batch script below as the `players.mpv.executable`. This fixes my issue.

\* Took me ages to figure this out. I think it's maybe trying to write a temporary file to the working directory, which it then deletes immediately. I can see something appear briefly by starting mpv in an empty folder and then hammering F5 in explorer lol.
### Code Snippet (optional)

```
cd %UserProfile%

start "" mpv.exe %*
```

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by Baldomo** [comment]
I understand your request, but I must ask why would you need such functionality? I'm unsure about the usefulness of such a feature for the following reasons:
- The current PWD where the process is started depends on the OS. On Windows it's system32 because the command host executable which spawns commands is located there. This is beneficial because system32 is not writable without admin privileges so a rogue process/malicious configuration cannot take over the directory or write random stuff there
- As you can see by the solution you found,`players.<player>.executable` can point to any executable script. At that point, the user is responsible for any unwanted disk access and `open-in-mpv` is not anymore

**Comment by Tremolo4** [comment]
Thanks for the response and thanks for this tool in general, love it!

> why would you need such functionality?
Just to reiterate what I've tried to describe in my first post: For some youtube videos, yt-dlp fails/hangs silently if it can't write to the working directory.

However, I have since found that specifying a temp directory for yt-dlp like so `--paths temp:%TMP%` fixes the problem as well.

**Comment by Baldomo** [comment]
I'm glad you found a solution that's working for you, I'll probably add this tip to the README under a "troubleshooting" section of some sorts. Just to double down on my point, I don't think running executables in the user's home dir by default  would be wise, as a malicious actor could sneak a fake player with an associated malicious configuration and get access to the user's home or other directories
