### ISSUE TITLE
question: Usage questions

### ISSUE THREAD

**Issue by Rafee-M** [Baldomo/open-in-mpv#34]
### Question Description

Hi, sorry if this is a basic question. But I am clear on how to set it up and use it

my config.yml file (the default one)

![image](https://github.com/user-attachments/assets/7415a9f1-491b-4e66-abf9-62f658ddd4be)

mpv already in path with the executables

![image](https://github.com/user-attachments/assets/06a4c2b3-2d74-49fc-8b34-1aae50e6216e)

I try to click on the exention, but nothing happens. Am I supposed to do something with the executables/ click on the .reg file?

![image](https://github.com/user-attachments/assets/b92185cb-6374-4c38-b63a-99d3aaf36bff)

Thanks for your time!

### Checklist:

- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Baldomo** [comment]
Thank you for using this project! I agree it may not be extremely clear from the README, but you need to run the .reg file as administrator for Window to register `open-in-mpv.exe` as a link opener. This will let the extension send special URLs to `open-in-mpv.exe`, then it should work just fine. If you have any other problems (since Windows is not generally being tested on due to lack of personal time and hardware), search among the other closed issues or just open a new one! Always happy to help.

**Comment by Rafee-M** [comment]
Thanks for the response. After installing the reg file, manually selecting the mpv.exe doesn't do anything

![image](https://github.com/user-attachments/assets/996d16de-e4b5-4655-ad4e-c44b93c88b89)

Clicking on the mpv option without the logo (which was the default) gives the following message.

![image](https://github.com/user-attachments/assets/f5725c57-69b9-4d61-9a3e-fa646309d548)

**Comment by Rafee-M** [comment]
It works now! Thanks. The main issue was putting the windows exe in `C:\ProgramData\open-in-mpv`
